xcopy Converter_Files "D:\MyProjects\paradoxGameConvertersForks\Vic2ToHoI4\Release\Vic2ToHoI4" /Y /Q /S
copy Saves\The_Roman_Empire1936_01_01.v2 "D:\MyProjects\paradoxGameConvertersForks\Vic2ToHoI4\Release\Vic2ToHoI4"
cd "D:\MyProjects\paradoxGameConvertersForks\Vic2ToHoI4\Release\Vic2ToHoI4"
V2ToHoI4Converter.exe The_Roman_Empire1936_01_01.v2

del results /S /Q
rmdir results /S /Q
mkdir results
xcopy "output\The_Roman_Empire1936_01_01" "D:\MyProjects\RomanHoI4\results\The_Roman_Empire1936_01_01" /E /Y /I /Q
copy "output\The_Roman_Empire1936_01_01.mod" "D:\MyProjects\RomanHoI4\results\"

cd "D:\MyProjects\RomanHoI4"
xcopy HoI4Mod results /E /Y /I /Q

"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/ALG - Algeria.txt" "HoI4Mod/patch/AlgeriaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/ANG - Angola.txt" "HoI4Mod/patch/AngolaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/AOT - Aoteorea.txt" "HoI4Mod/patch/AoteoreaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/AQI - Aquitaine.txt" "HoI4Mod/patch/AquitaineHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/ARM - Armenia.txt" "HoI4Mod/patch/ArmeniaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/AST - Australia.txt" "HoI4Mod/patch/AustraliaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/AZR - Azerbaijan.txt" "HoI4Mod/patch/AzerbaijanHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/BRG - Burgundy.txt" "HoI4Mod/patch/BurgundyHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/BRI - Brittany.txt" "HoI4Mod/patch/BrittanyHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/BRK - Burkina Faso.txt" "HoI4Mod/patch/BurkinaFasoHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/CAT - Catalonia.txt" "HoI4Mod/patch/CataloniaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/CHD - Chad.txt" "HoI4Mod/patch/ChadHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/CMR - Cameroon.txt" "HoI4Mod/patch/CameroonHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/CUB - Cuba.txt" "HoI4Mod/patch/CubaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/CRO - Pannonia.txt" "HoI4Mod/patch/PannoniaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/DAH - Dahomey.txt" "HoI4Mod/patch/DahomeyHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/EGY - Egypt.txt" "HoI4Mod/patch/EgyptHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/FLD - Flanders-Wallonia.txt" "HoI4Mod/patch/FlandersWalloniaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/FRA - France.txt" "HoI4Mod/patch/FranceHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/GAB - Gabon.txt" "HoI4Mod/patch/GabonHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/GEO - Georgia.txt" "HoI4Mod/patch/GeorgiaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/GRB - Great Britain.txt" "HoI4Mod/patch/GreatBritainHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/GUI - Guinea.txt" "HoI4Mod/patch/GuineaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/GUY - Guyenne.txt" "HoI4Mod/patch/GuyenneHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/ISR - Israel.txt" "HoI4Mod/patch/IsraelHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/ITA - Italy.txt" "HoI4Mod/patch/ItalyHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/JAV - Java.txt" "HoI4Mod/patch/JavaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/MAU - Mauritania.txt" "HoI4Mod/patch/MauritaniaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/MLI - Mali.txt" "HoI4Mod/patch/MaliHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/MOR - Morocco.txt" "HoI4Mod/patch/MoroccoHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/MOS - Moesia Inferior.txt" "HoI4Mod/patch/MoesiaInferiorHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/NGR - Niger.txt" "HoI4Mod/patch/NigerHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/NMB - Namibia.txt" "HoI4Mod/patch/NamibiaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/PHI - Philippines.txt" "HoI4Mod/patch/PhilippinesHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/RME - The Roman Empire.txt" "HoI4Mod/patch/RomeHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/SAF - South Africa.txt" "HoI4Mod/patch/SouthAfricaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/SEN - Senegal.txt" "HoI4Mod/patch/SenegalHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/SER - Moesia Superior.txt" "HoI4Mod/patch/MoesiaSuperiorHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/SIC - Sicily.txt" "HoI4Mod/patch/SicilyHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/SPA - Spain.txt" "HoI4Mod/patch/SpainHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/SWI - Raetia.txt" "HoI4Mod/patch/RaetiaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/SYR - Syria.txt" "HoI4Mod/patch/SyriaHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/TOG - Togo.txt" "HoI4Mod/patch/TogoHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/TRI - Tripoli.txt" "HoI4Mod/patch/TripoliHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/TUN - Tunis.txt" "HoI4Mod/patch/TunisHistory.patch"
"c:\Program Files (x86)\Beyond Compare 4\Patch.exe" "results/The_Roman_Empire1936_01_01/history/countries/YUG - Dalmatia.txt" "HoI4Mod/patch/DalmatiaHistory.patch"